---

- name: Configure the Remmina PPA
  apt_repository: repo="ppa:remmina-ppa-team/remmina-next" state=present

- name: Install Remmina
  apt: pkg="{{ item }}" state=present
  with_items:
    - remmina
    - remmina-plugin-rdp
