---
sudo: required
dist: bionic

language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"

env:
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  - ansible-playbook -v ubuntu.yml --syntax-check
