---

- name: Debian playbook
  hosts: localhost
  roles:
    - { role: apt-meta, become: true }
    - { role: common, become: true }
    - { role: docker, become: true }
    - { role: exfat-support, become: true }
    - { role: ssh, become: true }
    - { role: curl, become: true }
    - { role: htop, become: true }
    - { role: netcat, become: true }
    - { role: vagrant, become: true }
    - { role: virtualbox, become: true }
    - { role: wget, become: true }
    - { role: 7zip, become: true }
