---

- name: Ensure required packages are installed
  apt:
    state: present
    name: "{{ apt_repo_packages }}"
    update_cache: true
    install_recommends: false
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: true

- name: Ensure default sources.list is removed
  file:
    state: absent
    path: /etc/apt/sources.list
  become: true
  notify: update apt repo cache

- name: Ensure apt keys are managed
  apt_key:
    state: "{{ apt_repo_state }}"
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: true
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: true
  with_items:
    - "{{ apt_repo_keys }}"
  notify: update apt repo cache

- name: Ensure apt repositories are managed
  apt_repository:
    state: "{{ apt_repo_state }}"
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    validate_certs: true
    update_cache: true
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: true
  with_items:
    - "{{ apt_repo_repositories }}"
  notify: update apt repo cache

# Make sure the handler runs now and not at the end of the playbook
- meta: flush_handlers
