---

- name: Configure the Geary PPA
  apt_repository: repo="ppa:yorba/ppa" state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Install Geary
  apt: pkg="geary" state=latest

