---

- name: "{{ ssh.password_auth | ternary('Allow','Disallow') }} password authentication"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication {{ ssh.password_auth | ternary('yes','no') }}"
    state: present

- name: "{{ ssh.root_login | ternary('Allow','Disallow') }} root SSH access"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin {{ ssh.root_login | ternary('yes','no') }}"
    state: present

- name: "Ensure SSH is {{ ssh.start | ternary('started','stopped') }}"
  ansible.builtin.service:
    name: ssh
    state: "{{ ssh.start | ternary('restarted','stopped') }}"
    enabled: "{{ ssh.service_enabled }}"

- name: Secure port 22
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
  become: true
