---

- name: Clone sxhkd repository
  git: repo=https://github.com/baskerville/sxhkd.git dest="{{ ansible_env.HOME }}/.cache/install/sxhkd" update=yes accept_hostkey=yes
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: Install build dependencies
  apt: pkg="{{ item }}" state=latest
  with_items:
    - build-essential
    - libxcb-util0-dev
    - libxcb-keysyms1-dev

- name: Make
  command: make
  args:
    chdir: "{{ ansible_env.HOME }}/.cache/install/sxhkd"
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: Make install
  command: make install
  args:
    chdir: "{{ ansible_env.HOME }}/.cache/install/sxhkd"
