---

- name: Install standard desktop packages
  apt: pkg="{{ item }}" state=latest
  with_items:
    # Audio
    - alsa-base
    - pulseaudio
    - pavucontrol
    # Terminal
    - rxvt-unicode-256color
    # Image viewer et background manager
    - feh
    - gpicview
    # Themes manager
    - lxappearance
    - human-theme
    # File browser (+ autmount + network)
    - pcmanfm
    - ranger
    - udiskie
    - udisks2
    - gamin
    - policykit-1-gnome
    - gvfs
    # Music player
    - cmus
    # Videos player
    - mpv
    - vlc
    # Network management
    - network-manager
    - network-manager-gnome
    - gnome-keyring
    # System tray
    - trayer
    # Launcher
    - dmenu
    # Gtk engine
    - gtk2-engines-murrine
    # Fonts management
    - font-manager
    # Calc
    - gnome-calculator
    # Screenlocker
    - i3lock
    # Notification daemon
    - dunst
    # Others
    - dkms
    - gnome-themes-standard
    - xautolock
    - xcb
