---

- name: Check if XMind is installed
  command: dpkg-query -W xmind
  register: xmind_check_deb
  failed_when: xmind_check_deb.rc > 1
  changed_when: xmind_check_deb.rc == 1

- name: Download XMind
  get_url: url="http://www.xmind.net/xmind/downloads/xmind-7-update1-linux_amd64.deb" dest="/tmp/download-xmind-latest.deb"
  when: xmind_check_deb.rc == 1

- name: Install XMind
  apt: deb="/tmp/download-xmind-latest.deb"
  when: xmind_check_deb.rc == 1

- name: Clean XMind deb file
  file: path=/tmp/download-xmind-latest.deb state=absent
