---

- name: Set npm global packages path
  command: npm config set prefix "{{ ansible_env.HOME }}/.npm-packages"
  changed_when: false

- name: Installs BrowserSync globally using npm
  npm: name=browser-sync state=present global=yes
