---

- name: Create startup application directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Add new startup entries
  template: src=desktop.j2 dest="{{ ansible_env.HOME }}/.config/autostart/{{ item.name }}.desktop" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"
  with_items:
    - { name: "Psensor", exec: "psensor" }
    - { name: "Workday", exec: "{{ ansible_env.HOME }}/src/workday/workday.py" }
    - { name: "Caffeine", exec: "caffeine-indicator" }
    - { name: "Startup.sh", exec: "{{ ansible_env.HOME }}/startup.sh" }
