---

- name: Add pgp key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    
- name: Add repo
  become: true
  apt_repository:
    repo: 'deb {{ virtualbox_repository }}/debian {{ ansible_distribution_release }} contrib'
    state: present
    filename: virtualbox
    update_cache: true
  register: result
  until: result is succeeded
    
- name: Search current Virtualbox version
  uri:
    url: https://release-monitoring.org/api/project/14449
    return_content: true
  register: register_version
  delegate_to: localhost
  
- name: Set current Virtualbox version
  set_fact:
    current_version: "{{ register_version.json['version'] }}"
    
- name: Install Virtualbox
  become: true
  package:
    name: '{{ virtualbox_packages }}'
    state: present
  register: result
  until: result is successful
  
- name: Download Extension pack
  get_url:
    url: 'https://download.virtualbox.org/virtualbox/{{ current_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ current_version }}.vbox-extpack'
    dest: '{{ virtualbox_extension_pack_dest }}'
    
- name: Install Extension pack
  become: true
  shell: 'VBoxManage extpack install --replace --accept-license={{ virtualbox_extension_pack_license_hash }} {{ virtualbox_extension_pack_dest }}'