---

- name: Install Packages for Tmux
  apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - tmux
    - sudo
  become: yes

- name: Add .tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: '0660'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
