---

- name: Install Fail2ban
  apt: pkg=fail2ban state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: "Ensure Fail2ban is {{ fail2ban.start | ternary('started','stopped') }}"
  service: name=fail2ban state={{ fail2ban.start | ternary('restarted','stopped') }} enabled={{ fail2ban.service_enabled }}
