---

- name: Add MaIm repository
  apt_repository: repo="ppa:nilarimogard/webupd8" state=present

- name: Install MaIm
  apt: name=maim state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
