---

- name: Ensure the system can use the HTTPS transport for APT
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt: pkg=apt-transport-https state=installed
  when: not apt_https_transport.stat.exists

- name: Upgrade installed packages
  apt: upgrade=yes

- name: Install MOTD 1/2
  copy:
    src: 05-hostname
    dest: /etc/update-motd.d/05-hostname
    owner: "{{ ansible_user_id }}"
    mode: 0755

- name: Install MOTD 2/2
  copy:
    src: 60-services
    dest: /etc/update-motd.d/60-services
    owner: "{{ ansible_user_id }}"
    mode: 0755

- name: Edit Bash prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    line: 'export PS1="\[\e[31m\]x\[\e[m\]:\[\e[34m\]\w\[\e[m\]\[\e[37m\]\\$\[\e[m\] "'
    owner: "{{ ansible_user_id }}"
    
- name: Tune GPG
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    line: "{{ item }}"
    owner: "{{ ansible_user_id }}"
  with_items:
    - "GPG_TTY=$(tty)"
    - "export GPG_TTY"

- name:  Check for "admin" group
  group:
    name: admin
    state: present

- name: Populate admin group
  user:
    name: "{{ ansible_user_id }}"
    groups: admin
    append: yes

- name: Su for admin group
  shell: "dpkg-statoverride --update --add root admin 4750 /bin/su"
  become: true
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Restrict shared memory
  lineinfile:
    dest: /etc/fstab
    line: "none /run/shm tmpfs rw,noexec,nosuid,nodev 0 0"

- name: Allow ssh
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Limit ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
