---

- name: Install Vim
  apt: pkg=vim state=latest update_cache=yes
  become: true

- name: Create the "src" directory
  file: path="{{ ansible_env.HOME }}/src" state=directory

- name: Create Vim plugins dirs (pathogen
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ ansible_env.HOME }}/.vim/autoload"
    - "{{ ansible_env.HOME }}/.vim/bundle"

- name: Install Pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"
    mode: '0774'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Clone Vim Plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/{{ item.name }}"
    update: yes
    accept_hostkey: yes
  with_items:
    - { repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree }
    - { repo: "https://github.com/kien/ctrlp.vim.git", name: ctrlp }
    - { repo: "https://github.com/scrooloose/syntastic.git", name: syntastic }
    - { repo: "https://github.com/Lokaltog/vim-powerline.git", name: vim-powerline }
    - { repo: "https://github.com/ap/vim-css-color.git", name: vim-css-color }
    - { repo: "https://github.com/mattn/emmet-vim.git", name: emmet-vim }
    - { repo: "https://github.com/tpope/vim-surround.git", name: vim-surround }
    - { repo: "https://github.com/godlygeek/tabular.git", name: tabular }
    - { repo: "https://github.com/honza/vim-snippets.git", name: vim-snippets }
    - { repo: "https://github.com/joonty/vdebug.git", name: vdebug }
    - { repo: "https://github.com/majutsushi/tagbar.git", name: tagbar }
    - { repo: "https://github.com/joonty/vim-taggatron", name: vim-taggatron }
    - { repo: "https://github.com/shawncplus/phpcomplete.vim", name: phpcomplete }
    - { repo: "https://github.com/jedihe/tagbar-phpctags.vim", name: tagbar-phpctags }

- name: Add .vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0660'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Install required tools for building phpctags
  apt: pkg="{{ item }}" state=latest
  become: true
  with_items:
    - php
    - php-xml # resolves the error about the missing dom extension
    - automake # used for the ctags version with better php parser
    - make
    - gcc
    - curl

- name: Clone tagbar-phpctags
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/{{ item.name }}"
    update: yes
    accept_hostkey: yes
    version: update-phpctags-0.6.0
  with_items:
    - { repo: "https://github.com/jedihe/tagbar-phpctags.vim", name: tagbar-phpctags }

- name: Build tagbar-phpctags
  make:
    chdir: "{{ ansible_env.HOME }}/.vim/bundle/tagbar-phpctags"

- name: Copy Ctags .tar.gz from phpcomplete
  copy:
    src: "{{ ansible_env.HOME }}/.vim/bundle/phpcomplete/misc/ctags-5.8_better_php_parser.tar.gz"
    dest: "{{ ansible_env.HOME }}/src/ctags-5.8_better_php_parser.tar.gz"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Extract Ctags .tar.gz
  unarchive:
    src: "{{ ansible_env.HOME }}/.vim/bundle/phpcomplete/misc/ctags-5.8_better_php_parser.tar.gz"
    dest: "{{ ansible_env.HOME }}/src/"
    creates: "{{ ansible_env.HOME }}/src/ctags/Makefile.in"

- name: Compile Ctags from phpcomplete
  shell: |
    autoreconf -fi
    ./configure
    make -j $(nproc)
    make install
    make clean
  args:
    chdir: "{{ ansible_env.HOME }}/src/ctags"
    creates: /usr/local/bin/ctags
  become: yes
