name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: ansible/ansible-lint-action@master
      with:
        targets: debian.yml
        override-deps: ""
        args: ""