name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: ansible/ansible-lint-action@master
      with:
        targets: debian.yml
        override-deps: ""
        args: ""