---

- name: Install faenza icon theme
  apt: pkg=faenza-icon-theme state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true

- name: Install psutil
  apt: pkg="python-psutil" state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true

- name: Set 'Faenza-Ambiance' icon theme.
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Faenza-Ambiance'"
